
from typing import TypedDict, List, Optional, Literal


class ScreeningResult(TypedDict):
    """
    Represents the result of a candidate's initial screening process.

    Attributes:
        candidate_id (str): Unique identifier for the candidate.
        score (float): Screening score assigned to the candidate.
        decision (Literal["shortlist", "reject"]): Outcome of the screening.
        reasons (str): Explanation or justification for the decision.
    """
    candidate_id: str
    score: float
    decision: Literal["shortlist", "reject"]
    reasons: str


class InterviewRound(TypedDict):
    """
    Represents a single interview round for a candidate.

    Attributes:
        round_number (int): The sequence number of the interview round.
        slot (str): Scheduled time slot for the interview.
        feedback (str | None): Feedback provided by the interviewer, if any.
        decision (Literal["next_round", "reject", "offer"] | None):
            Decision made after this round.
    """
    round_number: int
    slot: str
    feedback: str | None
    decision: Literal["next_round", "reject", "offer"] | None


class CandidateInterview(TypedDict):
    """
    Represents the full interview lifecycle for a candidate.

    Attributes:
        candidate_id (str): Unique identifier for the candidate.
        status (Literal[
            "Pending_first_round",
            "waiting_feedback",
            "next_round_pending",
            "rejected",
            "offer_made"
        ]): Current status of the candidate in the interview pipeline.
        current_round (int): The round number the candidate is currently in.
        history (List[InterviewRound]): All completed interview rounds.
    """
    candidate_id: str
    status: Literal[
        "Pending_first_round",
        "waiting_feedback",
        "next_round_pending",
        "rejected",
        "offer_made"
    ]
    current_round: int
    history: List[InterviewRound]


class state(TypedDict):
    """
    Represents the overall state of the hiring agent.

    Attributes:
        job_id (str): Identifier for the job posting.
        job_description (str): Description of the job role.
        resume (list[str]): List of resume text segments or extracted fields.
        screening_result (list[ScreeningResult]): Results of candidate screening.
        interviews (list[CandidateInterview]): Interview progress for candidates.
        hr_report (str): Final HR summary or report generated by the agent.
    """
    job_id: str
    job_description: str
    resume: list[str]
    screening_result: list[ScreeningResult]
    interviews: list[CandidateInterview]
    hr_report: str
